### PR TITLE
Add AUTHOR

### LINKED ISSUE #6: Add AUTHORS
to list @mvdoc and others ;-)

### PR DESCRIPTION
**Pull request by mvdoc**
Closes #6 

Anyone else?

### CODE REVIEW

**Comment by mvdoc** [comment]
not here: https://docs.google.com/document/d/1EsQH3kVTdIstvjNoB-9vJxB8kGhtG4guKNaPVe-EP54

**Comment by yarikoptic** [comment]
That is reproin
Run git shortlog -sn

**Comment by mvdoc** [comment]
? this is reproin

```
    10  Yaroslav Halchenko
     1  Matteo Visconti dOC
```

**Comment by yarikoptic** [comment]
oh..  I mixed up the repos

**Pull request merged**
